@startuml
class CompanyManagement
class ServiceContract
class MenuView
class Menu
class CancelOption
class ShowOption
class ExitOption
class EnlargeOption
class ShiftOption
class GetCostOption

class Date
class DateView
class Console
class Interval

interface Option


CompanyManagement ..> ServiceContract
CompanyManagement ..> MenuView

ServiceContract ..> Date
ServiceContract *--> "360" Interval

MenuView --> ServiceContract
MenuView --> Menu
MenuView ..> Console

CancelOption ..> DateView
CancelOption ..> ServiceContract

EnlargeOption ..> DateView
ShiftOption ..> DateView

Menu --> ServiceContract
Menu --> Option
Menu --> CancelOption
Menu --> EnlargeOption
Menu --> ExitOption
Menu --> GetCostOption
Menu --> ShiftOption
Menu --> ShowOption

Option <|.. CancelOption
Option <|.. EnlargeOption
Option <|.. ExitOption
Option <|.. GetCostOption
Option <|.. ShiftOption
Option <|.. ShowOption


@enduml